config/routes.rb
Rails.application.routes.draw do
  resources :houses
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:name, :description, :image_url, :price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
    @featured_house = House.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/houses/_form.html.erb
<%= form_for(house) do |f| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="houses">
  <h1>Houses</h1>

  <div class="container-fluid">
    <div class="row" id="house">
      <% @houses.each do |house| %>
        <div class="col-sm-2 col-md-4">
          <h1><%= house.name %></h1>
          <div class="houseprice">
            $<%= house.price %>
          </div>
          <%= image_tag(house.image_url, class: "img-responsive") %>
          <p><%= house.description %></p>
        </div>
      <% end %>
    </div>
  </div>

<!-- <table>
  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.name %></td>
        <td><%= house.description %></td>
        <td><%= house.image_url %></td>
        <td><%= house.price %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %> -->

</div>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @house.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @house.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @house.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Propertiesgreece</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PropertiesGreece</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="../static_pages/index">Home<span class="sr-only">(current)</span></a></li>
            <li><a href="../static_pages/about">About</a></li>
            <li><a href="../houses">Houses</a></li>
            <li><a href="../static_pages/contact">Contact</a></li>
          </ul>
    </nav>

    <%= yield %>

    <footer>
      &copy; 2016 PropertiesGreece
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="about">
  <h1>About</h1>
  <h3>Our mission is to find you the house of your dreams in Greece.</h3>
  <p>Our company was established in 2016 after a high demand from foreingers to buy a property in Greece.</p>
  <p> Whether you are looking for a house in the mainland or in the islands, we have a solution for you.</p>
</div>

app/views/static_pages/contact.html.erb
<div class="contact">
  <div class="contact_intro">
    <h1>Contact</h1>
    <p>We are here for you. Find below the available contact options</p>
  </div>

  <div class="container" id="contact">
    <div class="container anchor" id="process">
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="email">
        <h3><span class="glyphicon glyphicon-envelope"></span>info@propertiesgreece.com</h3>
      </div> <!-- /email-->
      <div class="address">
        <h3><span class="glyphicon glyphicon-map-marker"></span>Anagnostou 22, Athens</h3>
      </div> <!-- /address-->
      <div class="phone">
        <h3><span class="glyphicon glyphicon-phone"></span>0030 210 5345 232</h3>
      </div> <!-- /phone -->
    </div>
    <div class="col-xs-12 col-md-6 myform">
      <form>
        <div class="form-group">
          <label class="sr-only" for="name">Name</label>
          <input class="form-control" placeholder="Enter your name" type="text" id="name">
        </div>
        <div class="form-group">
          <label class="sr-only" for="email">Email</label>
          <input class="form-control" title="mandatory field" placeholder="Enter your email address here" type="email" id="email" required="required">
        </div>
        <div class="form-group">
          <label class="sr-only" for="message">Message</label>
          <textarea class="form-control message-box" title="mandatory field" placeholder="Your message" style="resize:none" cols="40" rows="5" id="message" required="required"></textarea>
          <p id="visible-comment"></p>
          <p id="char-count"></p>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="homepage">
  <h1>Welcome to your new Home</h1>
  <h2>Find houses and property in Greece</h2>
  <p>Search through hundread of options and make your dream come true.</p>
  <div class="img_greece">
    <%= image_tag("greece.jpg", size: "800x600", class: "img-responsive") %>
  </div>
</div>

app/views/static_pages/landing_page.html.erb
<h2>Featured House:</h2>
<%= @featured_house.name %>